[package]
name = "stremio-addon-sdk"
version = "0.1.2"
authors = ["Ivo Georgiev <ivo@strem.io>", "Sleeyax <yourd3veloper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# As of 14 April, 2025
stremio-core = { git = "https://github.com/stremio/stremio-core", rev = "525a1a94963683dd64079d9bf1dd016d40027513", features = ["env-future-send"] }
# Hyper HTTP Server
hyper = { version = "^1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "^1", features = ["net"] }
serde_json = "1.0"
semver = { version = "1", features = ["serde"] }
futures = "0.3"
futures-util = "0.3"
percent-encoding = "1.0.1"  # Need old version to support encoding
url = { version = "2.4", features = ["serde"] }
# now_lambda = "0.1.3"
